# Generated by Django 3.2.5 on 2021-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['rating']},
        ),
        migrations.AlterField(
            model_name='anime',
            name='airing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('towatch', 'To Watch'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('onhold', 'On Hold')], default='towatch', max_length=100),
        ),
    ]
